name: airflow-tutorial
channels:
- !!python/unicode
  'defaults'
dependencies:
- !!python/unicode
  'openssl=1.0.2l=0'
- !!python/unicode
  'pip=9.0.1=py27_1'
- !!python/unicode
  'python=2.7.13=0'
- !!python/unicode
  'readline=6.2=2'
- !!python/unicode
  'setuptools=27.2.0=py27_0'
- !!python/unicode
  'sqlite=3.13.0=0'
- !!python/unicode
  'tk=8.5.18=0'
- !!python/unicode
  'wheel=0.29.0=py27_0'
- !!python/unicode
  'zlib=1.2.8=3'
- pip:
  - alembic==0.8.10
  - apache-airflow==1.8.1
  - certifi==2017.4.17
  - chardet==3.0.4
  - click==6.7
  - croniter==0.3.17
  - dill==0.2.7.1
  - docutils==0.13.1
  - flask==0.11.1
  - flask-admin==1.4.1
  - flask-cache==0.13.1
  - flask-login==0.2.11
  - flask-swagger==0.2.13
  - flask-wtf==0.12
  - funcsigs==1.0.0
  - future==0.15.2
  - gitdb2==2.0.2
  - gitpython==2.1.5
  - gunicorn==19.3.0
  - idna==2.5
  - itsdangerous==0.24
  - jinja2==2.8.1
  - lockfile==0.12.2
  - lxml==3.8.0
  - mako==1.0.7
  - markdown==2.6.8
  - markupsafe==1.0
  - numpy==1.13.1
  - ordereddict==1.1
  - pandas==0.20.3
  - psutil==4.4.2
  - pygments==2.2.0
  - python-daemon==2.1.2
  - python-dateutil==2.6.1
  - python-editor==1.0.3
  - python-nvd3==0.14.2
  - python-slugify==1.1.4
  - pytz==2017.2
  - pyyaml==3.12
  - requests==2.18.1
  - setproctitle==1.1.10
  - six==1.10.0
  - smmap2==2.0.3
  - sqlalchemy==1.1.11
  - tabulate==0.7.7
  - thrift==0.9.3
  - unidecode==0.4.21
  - urllib3==1.21.1
  - werkzeug==0.12.2
  - wtforms==2.1
  - zope.deprecation==4.2.0
